#Creating EFS Dynamic volume for nginx servie

#add PVC
#Claim: EFS-PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-dynamic-sc"
  resources:
    requests:
      storage: 3Gi
---
#add POD
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    purpose: practice-dynamic-efs
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1c
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-dynamic-pvc
---
#Add service
#ADd Service: EFS-SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: practice-dynamic-efs
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007