#ConfigMap:  refering the varibales in this pod.

apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:              #1st var:here it is reffreing with key:value pairs, means by giving key here and we will get value of key.
            configMapKeyRef:      #this is the keyword to refer from any ConfigMap resource
              name: nginx-config
              key: course
        - name: duration
          valueFrom:           #2nd var:here it is reffreing with key:value pairs, means by giving key here and we will get value of key.
            configMapKeyRef:         #this is the keyword to refer from any ConfigMap resource
              name: nginx-config
              key: duration