#Secret reourecs:  it is only encoding and pod will decode the given data,
#useranme is: echo "pavram" | base64    -->we will get the encoded uername:
#password is: echo "prasad143" | base64 ---> will get enoceded password

apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
type: opaque          # it the type of secret , you can use different type as well
data:
  username: "cGF2cmFtCg=="
  password: "cHJhc2FkMTQzCg=="