apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret
#   labels:
#     project: expense
#     tier: backend
#     environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret