#Secret resource -->refering in thid pod
#Keyword: - secretRef:
          #   name: <resource-secret-name>

apiVersion: v1
kind: Pod
metadata: 
  name: pod-sec
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret