apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    tier: backend
    environment: dev
  ports:
    - name: ngin-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
      