#LoadBalancer:: It open the the NodePort and LoadBalncer 
#User browse dns/ip and it hits the Loadbalancer, LB randomly hits the any of all healthy worker nodes for example: on port 31857 and it will goes Cluster IP and then it connects to pod.

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
      