#label:
apiVersion: v1
kind: Pod #Namesapce Service 
metadata:
  # name: label
  # labels:
  #   environment: dev
  #   project: expense
  #   tier: backend
  name: annotations-demo
  annotations:
    imageregistry: "https://telugudevops.online/"
    buildURL: "htpps://dockerhub.com/"
spec:
  containers:
    - name: nodejs
      image: nodejs:20
      env:
        - name: course
          value: "Devops with Azure"
        - name: hosted_zone
          value: "telugudevops.online"
        - name: mysql_password
          value: "ExpenseApp@1"
        
    - name: nginx
      image: nginx:8.0
      # ports:
      #   - port_number: 80

